//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Run "make generate" to regenerate after changing API types.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another.
func (in *JanitorPolicy) DeepCopyInto(out *JanitorPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of JanitorPolicy.
func (in *JanitorPolicy) DeepCopy() *JanitorPolicy {
	if in == nil {
		return nil
	}
	out := new(JanitorPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *JanitorPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another.
func (in *JanitorPolicyList) DeepCopyInto(out *JanitorPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JanitorPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of JanitorPolicyList.
func (in *JanitorPolicyList) DeepCopy() *JanitorPolicyList {
	if in == nil {
		return nil
	}
	out := new(JanitorPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *JanitorPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into out.
func (in *JanitorPolicySpec) DeepCopyInto(out *JanitorPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(TTLConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Protection != nil {
		in, out := &in.Protection, &out.Protection
		*out = new(ProtectionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Orphan != nil {
		in, out := &in.Orphan, &out.Orphan
		*out = new(OrphanConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PRNamespace != nil {
		in, out := &in.PRNamespace, &out.PRNamespace
		*out = new(PRNamespaceConfig)
		(*in).DeepCopyInto(*out)
	}
	out.Action = in.Action
	if in.Reporting != nil {
		in, out := &in.Reporting, &out.Reporting
		*out = new(ReportingConfig)
		**out = **in
	}
}

// DeepCopy creates a deep copy.
func (in *JanitorPolicySpec) DeepCopy() *JanitorPolicySpec {
	if in == nil {
		return nil
	}
	out := new(JanitorPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *JanitorPolicyStatus) DeepCopyInto(out *JanitorPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.Stats != nil {
		in, out := &in.Stats, &out.Stats
		*out = new(PolicyStats)
		**out = **in
	}
}

// DeepCopy creates a deep copy.
func (in *JanitorPolicyStatus) DeepCopy() *JanitorPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(JanitorPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]ResourceKind, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *TTLConfig) DeepCopyInto(out *TTLConfig) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy creates a deep copy.
func (in *TTLConfig) DeepCopy() *TTLConfig {
	if in == nil {
		return nil
	}
	out := new(TTLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *ProtectionConfig) DeepCopyInto(out *ProtectionConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy.
func (in *ProtectionConfig) DeepCopy() *ProtectionConfig {
	if in == nil {
		return nil
	}
	out := new(ProtectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *OrphanConfig) DeepCopyInto(out *OrphanConfig) {
	*out = *in
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ConfidenceThreshold != nil {
		in, out := &in.ConfidenceThreshold, &out.ConfidenceThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy creates a deep copy.
func (in *OrphanConfig) DeepCopy() *OrphanConfig {
	if in == nil {
		return nil
	}
	out := new(OrphanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *PRNamespaceConfig) DeepCopyInto(out *PRNamespaceConfig) {
	*out = *in
	if in.ClosedTTL != nil {
		in, out := &in.ClosedTTL, &out.ClosedTTL
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy creates a deep copy.
func (in *PRNamespaceConfig) DeepCopy() *PRNamespaceConfig {
	if in == nil {
		return nil
	}
	out := new(PRNamespaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *ActionConfig) DeepCopyInto(out *ActionConfig) {
	*out = *in
	if in.ConfidenceThreshold != nil {
		in, out := &in.ConfidenceThreshold, &out.ConfidenceThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy creates a deep copy.
func (in *ActionConfig) DeepCopy() *ActionConfig {
	if in == nil {
		return nil
	}
	out := new(ActionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *ReportingConfig) DeepCopyInto(out *ReportingConfig) {
	*out = *in
}

// DeepCopy creates a deep copy.
func (in *ReportingConfig) DeepCopy() *ReportingConfig {
	if in == nil {
		return nil
	}
	out := new(ReportingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *PolicyStats) DeepCopyInto(out *PolicyStats) {
	*out = *in
}

// DeepCopy creates a deep copy.
func (in *PolicyStats) DeepCopy() *PolicyStats {
	if in == nil {
		return nil
	}
	out := new(PolicyStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into out.
func (in *ResourceKind) DeepCopyInto(out *ResourceKind) {
	*out = *in
}

// DeepCopy creates a deep copy.
func (in *ResourceKind) DeepCopy() *ResourceKind {
	if in == nil {
		return nil
	}
	out := new(ResourceKind)
	in.DeepCopyInto(out)
	return out
}
